### PR TITLE
Fixes for IDA Pro's SDK 9.0

### PR DESCRIPTION
**Pull request by Patoke**
Fixes for compilation support on different compilers too

### CODE REVIEW

**Review by Yakov5776 — APPROVED** [review]
Thank you for this, would be nice to get this merged. @senator715

**Comment by senator715** [comment]
Thanks for these changes, I'll review them and push them in to the main branch, thanks again

**Comment by senator715** [comment]
Hello,

Really sorry for the delays, I'm currently reviewing the code, as it has compatability issues with older versions under 9 regarding binsearch, I've obtained ida 9 and will make the fixes before I push

**Comment by Patoke** [comment]
Hi!

Please note that ``bin_search3`` doesn't exist in IDA Pro 9.0 RC1, ``bin_search`` should be used instead!

Best regards.

**Comment by senator715** [comment]
Hello,

I see, are you able to print the output of IDA_SDK_VERSION?

**Comment by Patoke** [comment]
Hello,

Sorry for the very late response, IDA_SDK_VERSION only changes with the major IDA version change, meaning this value would only change when IDA 9.1 comes out (eventually becoming 910)

I'm unsure of any way to discern between the beta and RC1 versions of IDA but personally I believe the best course of action would be supporting the latest available version (RC1, bin_search) instead of the older, beta version (bin_search3), but of course, that's just me

Cheers!

**Pull request merged**
